<?php
/**
 * 自定义响应数据
 */

namespace App\Serializers;

use League\Fractal\Pagination\PaginatorInterface;
use League\Fractal\Serializer\ArraySerializer;

class NoDataArraySerializer extends ArraySerializer
{
    /**
     * Serialize a collection.
     */
    public function collection($resourceKey, array $data)
    {
        return $this->formatData($resourceKey, $data);
    }

    /**
     * Serialize an item.
     */
    public function item($resourceKey, array $data)
    {
        return $this->formatData($resourceKey, $data);
    }

    public function paginator(PaginatorInterface $paginator)
    {
        return parent::paginator($paginator); // TODO: Change the autogenerated stub
    }

    private function formatData($resourceKey, $data) {
        return [
            env('API_RETURN_STATUS_CODE') => 0,
            env('API_RETURN_MESSAGE') => env('API_RETURN_SUCCESS'),
            'result' => [$resourceKey ?? 'data' => $data]
        ];
    }
}